### ISSUE TITLE
Translation does not work when the destination language is Chinese

### ISSUE THREAD

**Issue by damnkiwi6120** [FixTweet/FxTwitter#580]
I tried to translate a tweet in Discord from English to Chinese, but it does not work no matter I append `/zh`, `/zh-tw` or `/tw`.  
You wrote `2-letter ISO language code`, so `zh` should work according to [this table](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes#Table). It did not work.  

It seems that this feature is mimicking the translate button on X, which would send the request to access the same feature on X.  
It would fill the language code in a request header field called `x-twitter-client-language` and a request body field called `destinationLanguage`.  
I have `zh-tw` in `x-twitter-client-language` header field, whereas I have `zh` in `destinationLanguage` body field.

**Comment by dangeredwolf** [comment]
Thank you for pointing this out! Twitter's API does decide what language to translate to based on `x-twitter-client-language`. This should work but yet it doesn't because for some reason Twitter will only accept `zh-cn` or `zh-tw`. Luckily, we already have a mechanism to auto-correct language codes so this was an easy fix.

`zh` -> `zh-cn` (Could possibly change to `zh-tw`  depending on user feedback)
`cn` -> `zh-cn`
`tw` -> `zh-tw` 

I also made a change to allow extended language codes so you will also be able to specify full specific language codes like `/zh-tw`, as the current behavior was only to allow 2-digit ISO language codes. Hope this helps!

**Comment by damnkiwi6120** [comment]
It works now! Thanks for the quick fix!
