### ISSUE TITLE
Feature : Support Timestamps for when a post/message was made.

### ISSUE THREAD

**Issue by epbenten** [FixTweet/FxTwitter#733]
Hello, there.

Having support for the timestamp would make this the ultimate tool.
I hope that musk hasn't made it garbage to retrieve.

**Comment by dangeredwolf** [comment]
This has been asked before. Unfortunately, afaik Discord does not provide us a way to pass through timestamps in a way that their custom handler for twitter.com/x.com links do.

This is a problem because
- If we use relative time (i.e. 8 minutes ago), it will never update and can be very wrong.
- If we use absolute time, we have no idea what time zone the end user lives in. We also don't know what date/time format to use for the end user. 

So yeah, we can fetch the timestamps just fine it's just too clunky not being able to present it to the user in a nice way.

**Comment by floogulinc** [comment]
You could use Discord formatted timestamps like you get from https://hammertime.cyou/ in the content of the embed I'm pretty sure.
