### ISSUE TITLE
No support for Community Notes in Fx Twitter API

### ISSUE THREAD

**Issue by baatochan** [FixTweet/FxTwitter#776]
Hi,
Thanks for your work on this API, it really does make using twitter on tg/dc easier.
I have noticed that fxtw api doesn't support community notes on twitter posts. i.fxtwitter.com instant view pages also doesn't show if a post contain a community notes or not. That's why I wanted to report it as a feature request as community notes are very often an important part of the post. I'm sorry if it has been already reported. 
Example tweet with community notes: https://twitter.com/GooglePlay/status/1784251162234880165

**Comment by dangeredwolf** [comment]
I've actually been wanting to implement this at some point anyway, I think it's a good idea

**Comment by dangeredwolf** [comment]
👀 ![image](https://github.com/FixTweet/FxTwitter/assets/2636265/6d23dd7b-a509-492c-b16d-5ed4c7f0a745)

**Comment by baatochan** [comment]
Thanks so much. I can confirm it works. Btw is it possible that `tweet.community_note.entities.entity.ref.type` would be something different than URL (`TimelineUrl`)?

**Comment by dangeredwolf** [comment]
So for context, an annoying thing is that unfortunately unlike for links in a tweet, the api doesn't provide extended urls for community notes, only the t.co links. For now I've just passed through the entities from the twitter api directly.

But to answer your question... _Probably not_, **but** it's possible the Twitter API could pass through different types in the future.

Also ngl I kinda forgot I already published community notes in the public api since I haven't documented it yet.... Oops. I guess that's what I get for staying up until 4 am working on this xdd

Should I leave it as-is so if for whatever reason they add more it'll be instantly available or should I simplify it to a simpler, stable `url_entities` that validates the type is TimelineUrl (or equivalent) beforehand? I'm kind of leaning towards the latter for consistency with the rest of FixTweet's API but like I said I already published the change to the api without documenting it, oops.
