### ISSUE TITLE
Add option to posts with images to embed direct links with the `name=orig` attribute of the original image

### ISSUE THREAD

**Issue by szero** [FixTweet/FxTwitter#807]
So when someone embeds a post with multiple images, it create the mosaic of the images and in order to get the full resolution images separately, you need to open the tweet and open each image in new tab to get the full size pictures. Would be nice to have those links embedded in a tweet already for image posts or have it as an option with subdomain.

**Comment by dangeredwolf** [comment]
One workaround is that if you are Discord desktop, you can use `m.fxtwitter.com` (or `m.fixupx.com`) to be able to open individual images. The only reason this is not the default is because it does not work on mobile Discord, only desktop. You can also directly link a single image directly using the native syntax (i.e. /photo/2 for the 2nd image) Hope this helps!

**Comment by szero** [comment]
Thanks, it does exactly what I wanted it to, worth adding this info to your main readme since this subdomain option isn't listed there.
