### ISSUE TITLE
Video doesn’t play on IOS - Discord

### ISSUE THREAD

**Issue by Abdousoussi** [FixTweet/FxTwitter#859]
Exactly what the title says. Videos no longer play on discord for some reason. I tap them, but it just full screens the frame that the embed was in and keeps buffering.

Im using the latest discord and I’m using an IPhone 13 Pro

**Comment by umbra3275** [comment]
I also am experiencing this. It seems to be intermittent though, as some videos play and some others don't. Downloading the videos, some of them appear to be fragmented mp4 files? I'm not sure if that's the reason though.

**Comment by umbra3275** [comment]
https://fxtwitter.com/sleepychux/status/1806053249654423899
here's a link that doesn't play on IOS for me

**Comment by dangeredwolf** [comment]
That’s really interesting, I’ll have to test this out later today and see if that’s all it takes. Thanks for the tip!

**Comment by dangeredwolf** [comment]
Thanks for the tip @Delphox as I haven't noticed that workaround was so simple <.<

**Comment by Delphox** [comment]
Thanks for implementing it! One last thing, you should also do the same on GIFs. They're susceptible to the same issue (just tested seeking on an unbuffed gif and it has the same issue so I assume its also broken on iOS) but since they're already proxied it should be just a matter of stripping the extension.

**Comment by dangeredwolf** [comment]
Ah yes, I made a subtle change to fix this https://github.com/FixTweet/FxTwitter/commit/966ffd0eceb667f2c2775b66fd64e616a058844b
